//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegendaryArmory.Strings {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lore {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lore() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("LegendaryArmory.Strings.Lore", typeof(Lore).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string _83162 {
            get {
                return ResourceManager.GetString(":83162", resourceCulture);
            }
        }
        
        internal static string _93105 {
            get {
                return ResourceManager.GetString(":93105", resourceCulture);
            }
        }
        
        internal static string _80111 {
            get {
                return ResourceManager.GetString(":80111", resourceCulture);
            }
        }
        
        internal static string _72713 {
            get {
                return ResourceManager.GetString(":72713", resourceCulture);
            }
        }
        
        internal static string _83036 {
            get {
                return ResourceManager.GetString(":83036", resourceCulture);
            }
        }
        
        internal static string _89094 {
            get {
                return ResourceManager.GetString(":89094", resourceCulture);
            }
        }
        
        internal static string _84546 {
            get {
                return ResourceManager.GetString(":84546", resourceCulture);
            }
        }
        
        internal static string _80384 {
            get {
                return ResourceManager.GetString(":80384", resourceCulture);
            }
        }
        
        internal static string _30698 {
            get {
                return ResourceManager.GetString(":30698", resourceCulture);
            }
        }
        
        internal static string _101570 {
            get {
                return ResourceManager.GetString(":101570", resourceCulture);
            }
        }
        
        internal static string _77474 {
            get {
                return ResourceManager.GetString(":77474", resourceCulture);
            }
        }
        
        internal static string _30686 {
            get {
                return ResourceManager.GetString(":30686", resourceCulture);
            }
        }
        
        internal static string _87687 {
            get {
                return ResourceManager.GetString(":87687", resourceCulture);
            }
        }
        
        internal static string _83921 {
            get {
                return ResourceManager.GetString(":83921", resourceCulture);
            }
        }
        
        internal static string _82670 {
            get {
                return ResourceManager.GetString(":82670", resourceCulture);
            }
        }
        
        internal static string _80254 {
            get {
                return ResourceManager.GetString(":80254", resourceCulture);
            }
        }
        
        internal static string _84748 {
            get {
                return ResourceManager.GetString(":84748", resourceCulture);
            }
        }
        
        internal static string _82180 {
            get {
                return ResourceManager.GetString(":82180", resourceCulture);
            }
        }
        
        internal static string _81839 {
            get {
                return ResourceManager.GetString(":81839", resourceCulture);
            }
        }
        
        internal static string _91505 {
            get {
                return ResourceManager.GetString(":91505", resourceCulture);
            }
        }
        
        internal static string _91048 {
            get {
                return ResourceManager.GetString(":91048", resourceCulture);
            }
        }
        
        internal static string _80252 {
            get {
                return ResourceManager.GetString(":80252", resourceCulture);
            }
        }
        
        internal static string _30702 {
            get {
                return ResourceManager.GetString(":30702", resourceCulture);
            }
        }
        
        internal static string _82994 {
            get {
                return ResourceManager.GetString(":82994", resourceCulture);
            }
        }
        
        internal static string _83482 {
            get {
                return ResourceManager.GetString(":83482", resourceCulture);
            }
        }
        
        internal static string _89101 {
            get {
                return ResourceManager.GetString(":89101", resourceCulture);
            }
        }
        
        internal static string _101536 {
            get {
                return ResourceManager.GetString(":101536", resourceCulture);
            }
        }
        
        internal static string _79802 {
            get {
                return ResourceManager.GetString(":79802", resourceCulture);
            }
        }
        
        internal static string _83497 {
            get {
                return ResourceManager.GetString(":83497", resourceCulture);
            }
        }
        
        internal static string _83595 {
            get {
                return ResourceManager.GetString(":83595", resourceCulture);
            }
        }
        
        internal static string _82268 {
            get {
                return ResourceManager.GetString(":82268", resourceCulture);
            }
        }
        
        internal static string _89158 {
            get {
                return ResourceManager.GetString(":89158", resourceCulture);
            }
        }
        
        internal static string _91536 {
            get {
                return ResourceManager.GetString(":91536", resourceCulture);
            }
        }
        
        internal static string _95612 {
            get {
                return ResourceManager.GetString(":95612", resourceCulture);
            }
        }
        
        internal static string _82903 {
            get {
                return ResourceManager.GetString(":82903", resourceCulture);
            }
        }
        
        internal static string _83087 {
            get {
                return ResourceManager.GetString(":83087", resourceCulture);
            }
        }
        
        internal static string _81462 {
            get {
                return ResourceManager.GetString(":81462", resourceCulture);
            }
        }
        
        internal static string _82410 {
            get {
                return ResourceManager.GetString(":82410", resourceCulture);
            }
        }
        
        internal static string _101535 {
            get {
                return ResourceManager.GetString(":101535", resourceCulture);
            }
        }
        
        internal static string _84643 {
            get {
                return ResourceManager.GetString(":84643", resourceCulture);
            }
        }
        
        internal static string _89134 {
            get {
                return ResourceManager.GetString(":89134", resourceCulture);
            }
        }
        
        internal static string _81206 {
            get {
                return ResourceManager.GetString(":81206", resourceCulture);
            }
        }
        
        internal static string _97099 {
            get {
                return ResourceManager.GetString(":97099", resourceCulture);
            }
        }
        
        internal static string _83729 {
            get {
                return ResourceManager.GetString(":83729", resourceCulture);
            }
        }
        
        internal static string _30684 {
            get {
                return ResourceManager.GetString(":30684", resourceCulture);
            }
        }
        
        internal static string _82401 {
            get {
                return ResourceManager.GetString(":82401", resourceCulture);
            }
        }
        
        internal static string _80161 {
            get {
                return ResourceManager.GetString(":80161", resourceCulture);
            }
        }
        
        internal static string _89245 {
            get {
                return ResourceManager.GetString(":89245", resourceCulture);
            }
        }
        
        internal static string _83308 {
            get {
                return ResourceManager.GetString(":83308", resourceCulture);
            }
        }
        
        internal static string _30697 {
            get {
                return ResourceManager.GetString(":30697", resourceCulture);
            }
        }
        
        internal static string _97077 {
            get {
                return ResourceManager.GetString(":97077", resourceCulture);
            }
        }
        
        internal static string _90551 {
            get {
                return ResourceManager.GetString(":90551", resourceCulture);
            }
        }
        
        internal static string _83113 {
            get {
                return ResourceManager.GetString(":83113", resourceCulture);
            }
        }
        
        internal static string _84181 {
            get {
                return ResourceManager.GetString(":84181", resourceCulture);
            }
        }
        
        internal static string _84561 {
            get {
                return ResourceManager.GetString(":84561", resourceCulture);
            }
        }
        
        internal static string _96221 {
            get {
                return ResourceManager.GetString(":96221", resourceCulture);
            }
        }
        
        internal static string _80248 {
            get {
                return ResourceManager.GetString(":80248", resourceCulture);
            }
        }
        
        internal static string _101609 {
            get {
                return ResourceManager.GetString(":101609", resourceCulture);
            }
        }
        
        internal static string _89167 {
            get {
                return ResourceManager.GetString(":89167", resourceCulture);
            }
        }
        
        internal static string _82437 {
            get {
                return ResourceManager.GetString(":82437", resourceCulture);
            }
        }
        
        internal static string _95380 {
            get {
                return ResourceManager.GetString(":95380", resourceCulture);
            }
        }
        
        internal static string _83862 {
            get {
                return ResourceManager.GetString(":83862", resourceCulture);
            }
        }
        
        internal static string _96028 {
            get {
                return ResourceManager.GetString(":96028", resourceCulture);
            }
        }
        
        internal static string _83394 {
            get {
                return ResourceManager.GetString(":83394", resourceCulture);
            }
        }
        
        internal static string _82552 {
            get {
                return ResourceManager.GetString(":82552", resourceCulture);
            }
        }
        
        internal static string _83323 {
            get {
                return ResourceManager.GetString(":83323", resourceCulture);
            }
        }
        
        internal static string _84341 {
            get {
                return ResourceManager.GetString(":84341", resourceCulture);
            }
        }
        
        internal static string _30701 {
            get {
                return ResourceManager.GetString(":30701", resourceCulture);
            }
        }
        
        internal static string _84176 {
            get {
                return ResourceManager.GetString(":84176", resourceCulture);
            }
        }
        
        internal static string _84110 {
            get {
                return ResourceManager.GetString(":84110", resourceCulture);
            }
        }
        
        internal static string _89234 {
            get {
                return ResourceManager.GetString(":89234", resourceCulture);
            }
        }
        
        internal static string _89854 {
            get {
                return ResourceManager.GetString(":89854", resourceCulture);
            }
        }
        
        internal static string _30690 {
            get {
                return ResourceManager.GetString(":30690", resourceCulture);
            }
        }
        
        internal static string _83676 {
            get {
                return ResourceManager.GetString(":83676", resourceCulture);
            }
        }
        
        internal static string _30700 {
            get {
                return ResourceManager.GetString(":30700", resourceCulture);
            }
        }
        
        internal static string _83094 {
            get {
                return ResourceManager.GetString(":83094", resourceCulture);
            }
        }
        
        internal static string _82272 {
            get {
                return ResourceManager.GetString(":82272", resourceCulture);
            }
        }
        
        internal static string _30692 {
            get {
                return ResourceManager.GetString(":30692", resourceCulture);
            }
        }
        
        internal static string _84427 {
            get {
                return ResourceManager.GetString(":84427", resourceCulture);
            }
        }
        
        internal static string _30694 {
            get {
                return ResourceManager.GetString(":30694", resourceCulture);
            }
        }
        
        internal static string _89266 {
            get {
                return ResourceManager.GetString(":89266", resourceCulture);
            }
        }
        
        internal static string _83702 {
            get {
                return ResourceManager.GetString(":83702", resourceCulture);
            }
        }
        
        internal static string _89126 {
            get {
                return ResourceManager.GetString(":89126", resourceCulture);
            }
        }
        
        internal static string _82465 {
            get {
                return ResourceManager.GetString(":82465", resourceCulture);
            }
        }
        
        internal static string _80557 {
            get {
                return ResourceManager.GetString(":80557", resourceCulture);
            }
        }
        
        internal static string _82902 {
            get {
                return ResourceManager.GetString(":82902", resourceCulture);
            }
        }
        
        internal static string _82456 {
            get {
                return ResourceManager.GetString(":82456", resourceCulture);
            }
        }
        
        internal static string _84629 {
            get {
                return ResourceManager.GetString(":84629", resourceCulture);
            }
        }
        
        internal static string _83957 {
            get {
                return ResourceManager.GetString(":83957", resourceCulture);
            }
        }
        
        internal static string _89209 {
            get {
                return ResourceManager.GetString(":89209", resourceCulture);
            }
        }
        
        internal static string _91234 {
            get {
                return ResourceManager.GetString(":91234", resourceCulture);
            }
        }
        
        internal static string _84578 {
            get {
                return ResourceManager.GetString(":84578", resourceCulture);
            }
        }
        
        internal static string _101568 {
            get {
                return ResourceManager.GetString(":101568", resourceCulture);
            }
        }
        
        internal static string _80131 {
            get {
                return ResourceManager.GetString(":80131", resourceCulture);
            }
        }
        
        internal static string _83348 {
            get {
                return ResourceManager.GetString(":83348", resourceCulture);
            }
        }
        
        internal static string _30693 {
            get {
                return ResourceManager.GetString(":30693", resourceCulture);
            }
        }
        
        internal static string _80281 {
            get {
                return ResourceManager.GetString(":80281", resourceCulture);
            }
        }
        
        internal static string _86098 {
            get {
                return ResourceManager.GetString(":86098", resourceCulture);
            }
        }
        
        internal static string _82093 {
            get {
                return ResourceManager.GetString(":82093", resourceCulture);
            }
        }
        
        internal static string _83289 {
            get {
                return ResourceManager.GetString(":83289", resourceCulture);
            }
        }
        
        internal static string _80435 {
            get {
                return ResourceManager.GetString(":80435", resourceCulture);
            }
        }
        
        internal static string _30687 {
            get {
                return ResourceManager.GetString(":30687", resourceCulture);
            }
        }
        
        internal static string _30704 {
            get {
                return ResourceManager.GetString(":30704", resourceCulture);
            }
        }
        
        internal static string _89093 {
            get {
                return ResourceManager.GetString(":89093", resourceCulture);
            }
        }
        
        internal static string _89260 {
            get {
                return ResourceManager.GetString(":89260", resourceCulture);
            }
        }
        
        internal static string _101602 {
            get {
                return ResourceManager.GetString(":101602", resourceCulture);
            }
        }
        
        internal static string _84508 {
            get {
                return ResourceManager.GetString(":84508", resourceCulture);
            }
        }
        
        internal static string _30689 {
            get {
                return ResourceManager.GetString(":30689", resourceCulture);
            }
        }
        
        internal static string _97377 {
            get {
                return ResourceManager.GetString(":97377", resourceCulture);
            }
        }
        
        internal static string _82925 {
            get {
                return ResourceManager.GetString(":82925", resourceCulture);
            }
        }
        
        internal static string _80145 {
            get {
                return ResourceManager.GetString(":80145", resourceCulture);
            }
        }
        
        internal static string _82963 {
            get {
                return ResourceManager.GetString(":82963", resourceCulture);
            }
        }
        
        internal static string _80296 {
            get {
                return ResourceManager.GetString(":80296", resourceCulture);
            }
        }
        
        internal static string _82245 {
            get {
                return ResourceManager.GetString(":82245", resourceCulture);
            }
        }
        
        internal static string _89235 {
            get {
                return ResourceManager.GetString(":89235", resourceCulture);
            }
        }
        
        internal static string _82173 {
            get {
                return ResourceManager.GetString(":82173", resourceCulture);
            }
        }
        
        internal static string _84461 {
            get {
                return ResourceManager.GetString(":84461", resourceCulture);
            }
        }
        
        internal static string _82348 {
            get {
                return ResourceManager.GetString(":82348", resourceCulture);
            }
        }
        
        internal static string _30696 {
            get {
                return ResourceManager.GetString(":30696", resourceCulture);
            }
        }
        
        internal static string _89174 {
            get {
                return ResourceManager.GetString(":89174", resourceCulture);
            }
        }
        
        internal static string _84633 {
            get {
                return ResourceManager.GetString(":84633", resourceCulture);
            }
        }
        
        internal static string _84301 {
            get {
                return ResourceManager.GetString(":84301", resourceCulture);
            }
        }
        
        internal static string _101516 {
            get {
                return ResourceManager.GetString(":101516", resourceCulture);
            }
        }
        
        internal static string _96652 {
            get {
                return ResourceManager.GetString(":96652", resourceCulture);
            }
        }
        
        internal static string _84481 {
            get {
                return ResourceManager.GetString(":84481", resourceCulture);
            }
        }
        
        internal static string _97590 {
            get {
                return ResourceManager.GetString(":97590", resourceCulture);
            }
        }
        
        internal static string _96203 {
            get {
                return ResourceManager.GetString(":96203", resourceCulture);
            }
        }
        
        internal static string _82109 {
            get {
                return ResourceManager.GetString(":82109", resourceCulture);
            }
        }
        
        internal static string _82423 {
            get {
                return ResourceManager.GetString(":82423", resourceCulture);
            }
        }
        
        internal static string _89183 {
            get {
                return ResourceManager.GetString(":89183", resourceCulture);
            }
        }
        
        internal static string _30688 {
            get {
                return ResourceManager.GetString(":30688", resourceCulture);
            }
        }
        
        internal static string _71383 {
            get {
                return ResourceManager.GetString(":71383", resourceCulture);
            }
        }
        
        internal static string _101462 {
            get {
                return ResourceManager.GetString(":101462", resourceCulture);
            }
        }
        
        internal static string _82102 {
            get {
                return ResourceManager.GetString(":82102", resourceCulture);
            }
        }
        
        internal static string _97783 {
            get {
                return ResourceManager.GetString(":97783", resourceCulture);
            }
        }
        
        internal static string _83929 {
            get {
                return ResourceManager.GetString(":83929", resourceCulture);
            }
        }
        
        internal static string _80488 {
            get {
                return ResourceManager.GetString(":80488", resourceCulture);
            }
        }
        
        internal static string _101556 {
            get {
                return ResourceManager.GetString(":101556", resourceCulture);
            }
        }
        
        internal static string _83240 {
            get {
                return ResourceManager.GetString(":83240", resourceCulture);
            }
        }
        
        internal static string _82801 {
            get {
                return ResourceManager.GetString(":82801", resourceCulture);
            }
        }
        
        internal static string _80190 {
            get {
                return ResourceManager.GetString(":80190", resourceCulture);
            }
        }
        
        internal static string _84723 {
            get {
                return ResourceManager.GetString(":84723", resourceCulture);
            }
        }
        
        internal static string _81957 {
            get {
                return ResourceManager.GetString(":81957", resourceCulture);
            }
        }
        
        internal static string _78556 {
            get {
                return ResourceManager.GetString(":78556", resourceCulture);
            }
        }
        
        internal static string _89252 {
            get {
                return ResourceManager.GetString(":89252", resourceCulture);
            }
        }
        
        internal static string _30685 {
            get {
                return ResourceManager.GetString(":30685", resourceCulture);
            }
        }
        
        internal static string _101544 {
            get {
                return ResourceManager.GetString(":101544", resourceCulture);
            }
        }
        
        internal static string _101521 {
            get {
                return ResourceManager.GetString(":101521", resourceCulture);
            }
        }
        
        internal static string _83127 {
            get {
                return ResourceManager.GetString(":83127", resourceCulture);
            }
        }
        
        internal static string _82334 {
            get {
                return ResourceManager.GetString(":82334", resourceCulture);
            }
        }
        
        internal static string _82214 {
            get {
                return ResourceManager.GetString(":82214", resourceCulture);
            }
        }
        
        internal static string _84655 {
            get {
                return ResourceManager.GetString(":84655", resourceCulture);
            }
        }
        
        internal static string _30691 {
            get {
                return ResourceManager.GetString(":30691", resourceCulture);
            }
        }
        
        internal static string _82519 {
            get {
                return ResourceManager.GetString(":82519", resourceCulture);
            }
        }
        
        internal static string _76158 {
            get {
                return ResourceManager.GetString(":76158", resourceCulture);
            }
        }
        
        internal static string _101551 {
            get {
                return ResourceManager.GetString(":101551", resourceCulture);
            }
        }
        
        internal static string _83699 {
            get {
                return ResourceManager.GetString(":83699", resourceCulture);
            }
        }
        
        internal static string _82698 {
            get {
                return ResourceManager.GetString(":82698", resourceCulture);
            }
        }
        
        internal static string _95675 {
            get {
                return ResourceManager.GetString(":95675", resourceCulture);
            }
        }
        
        internal static string _30703 {
            get {
                return ResourceManager.GetString(":30703", resourceCulture);
            }
        }
        
        internal static string _101579 {
            get {
                return ResourceManager.GetString(":101579", resourceCulture);
            }
        }
        
        internal static string _89117 {
            get {
                return ResourceManager.GetString(":89117", resourceCulture);
            }
        }
        
        internal static string _81908 {
            get {
                return ResourceManager.GetString(":81908", resourceCulture);
            }
        }
        
        internal static string _82098 {
            get {
                return ResourceManager.GetString(":82098", resourceCulture);
            }
        }
        
        internal static string _80277 {
            get {
                return ResourceManager.GetString(":80277", resourceCulture);
            }
        }
        
        internal static string _103815 {
            get {
                return ResourceManager.GetString(":103815", resourceCulture);
            }
        }
        
        internal static string _96356 {
            get {
                return ResourceManager.GetString(":96356", resourceCulture);
            }
        }
        
        internal static string _82512 {
            get {
                return ResourceManager.GetString(":82512", resourceCulture);
            }
        }
        
        internal static string _101645 {
            get {
                return ResourceManager.GetString(":101645", resourceCulture);
            }
        }
        
        internal static string _30699 {
            get {
                return ResourceManager.GetString(":30699", resourceCulture);
            }
        }
        
        internal static string _88576 {
            get {
                return ResourceManager.GetString(":88576", resourceCulture);
            }
        }
        
        internal static string _80205 {
            get {
                return ResourceManager.GetString(":80205", resourceCulture);
            }
        }
        
        internal static string _80578 {
            get {
                return ResourceManager.GetString(":80578", resourceCulture);
            }
        }
        
        internal static string _95684 {
            get {
                return ResourceManager.GetString(":95684", resourceCulture);
            }
        }
        
        internal static string _82196 {
            get {
                return ResourceManager.GetString(":82196", resourceCulture);
            }
        }
        
        internal static string _80356 {
            get {
                return ResourceManager.GetString(":80356", resourceCulture);
            }
        }
        
        internal static string _89152 {
            get {
                return ResourceManager.GetString(":89152", resourceCulture);
            }
        }
        
        internal static string _30695 {
            get {
                return ResourceManager.GetString(":30695", resourceCulture);
            }
        }
        
        internal static string _79562 {
            get {
                return ResourceManager.GetString(":79562", resourceCulture);
            }
        }
        
        internal static string _92991 {
            get {
                return ResourceManager.GetString(":92991", resourceCulture);
            }
        }
        
        internal static string _95808 {
            get {
                return ResourceManager.GetString(":95808", resourceCulture);
            }
        }
        
        internal static string _101501 {
            get {
                return ResourceManager.GetString(":101501", resourceCulture);
            }
        }
        
        internal static string _101614 {
            get {
                return ResourceManager.GetString(":101614", resourceCulture);
            }
        }
        
        internal static string _101499 {
            get {
                return ResourceManager.GetString(":101499", resourceCulture);
            }
        }
        
        internal static string _80399 {
            get {
                return ResourceManager.GetString(":80399", resourceCulture);
            }
        }
        
        internal static string _101460 {
            get {
                return ResourceManager.GetString(":101460", resourceCulture);
            }
        }
        
        internal static string _87109 {
            get {
                return ResourceManager.GetString(":87109", resourceCulture);
            }
        }
        
        internal static string _82502 {
            get {
                return ResourceManager.GetString(":82502", resourceCulture);
            }
        }
        
        internal static string _96937 {
            get {
                return ResourceManager.GetString(":96937", resourceCulture);
            }
        }
        
        internal static string _74155 {
            get {
                return ResourceManager.GetString(":74155", resourceCulture);
            }
        }
        
        internal static string _97165 {
            get {
                return ResourceManager.GetString(":97165", resourceCulture);
            }
        }
        
        internal static string _101582 {
            get {
                return ResourceManager.GetString(":101582", resourceCulture);
            }
        }
        
        internal static string _105317 {
            get {
                return ResourceManager.GetString(":105317", resourceCulture);
            }
        }
        
        internal static string _105293 {
            get {
                return ResourceManager.GetString(":105293", resourceCulture);
            }
        }
        
        internal static string _105171 {
            get {
                return ResourceManager.GetString(":105171", resourceCulture);
            }
        }
        
        internal static string _106273 {
            get {
                return ResourceManager.GetString(":106273", resourceCulture);
            }
        }
        
        internal static string _105653 {
            get {
                return ResourceManager.GetString(":105653", resourceCulture);
            }
        }
        
        internal static string _105921 {
            get {
                return ResourceManager.GetString(":105921", resourceCulture);
            }
        }
        
        internal static string _106658 {
            get {
                return ResourceManager.GetString(":106658", resourceCulture);
            }
        }
        
        internal static string _106178 {
            get {
                return ResourceManager.GetString(":106178", resourceCulture);
            }
        }
    }
}
