//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegendaryArmory.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lore {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lore() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LegendaryArmory.Strings.Lore", typeof(Lore).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Feels nigh impenetrable. But I reckon the look of this alone will send most of your enemies running.&quot; —Lyhr, Facet of Logic
        ///
        ///&quot;Those who don&apos;t run&apos;ll just bounce off, eh?&quot; —Lyhr, Facet of Emotion.
        /// </summary>
        internal static string _101460 {
            get {
                return ResourceManager.GetString(":101460", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Impressive materials. Strong, flexible. Sharp look, too. I reckon you could wear this in battle and then wear it to court.&quot; —Lyhr, Facet of Logic
        ///
        ///&quot;Clean the blood off first.&quot; —Lyhr, Facet of Emotion.
        /// </summary>
        internal static string _101462 {
            get {
                return ResourceManager.GetString(":101462", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Impressive materials. Strong, flexible. Sharp look, too. I reckon you could wear this in battle and then wear it to court.&quot; —Lyhr, Facet of Logic
        ///
        ///&quot;Clean the blood off first.&quot; —Lyhr, Facet of Emotion.
        /// </summary>
        internal static string _101499 {
            get {
                return ResourceManager.GetString(":101499", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Impressive materials. Strong, flexible. Sharp look, too. I reckon you could wear this in battle and then wear it to court.&quot; —Lyhr, Facet of Logic
        ///
        ///&quot;Clean the blood off first.&quot; —Lyhr, Facet of Emotion.
        /// </summary>
        internal static string _101501 {
            get {
                return ResourceManager.GetString(":101501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Impressive materials. Strong, flexible. Sharp look, too. I reckon you could wear this in battle and then wear it to court.&quot; —Lyhr, Facet of Logic
        ///
        ///&quot;Clean the blood off first.&quot; —Lyhr, Facet of Emotion.
        /// </summary>
        internal static string _101516 {
            get {
                return ResourceManager.GetString(":101516", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Feels nigh impenetrable. But I reckon the look of this alone will send most of your enemies running.&quot; —Lyhr, Facet of Logic
        ///
        ///&quot;Those who don&apos;t run&apos;ll just bounce off, eh?&quot; —Lyhr, Facet of Emotion.
        /// </summary>
        internal static string _101521 {
            get {
                return ResourceManager.GetString(":101521", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Impressive materials. Strong, flexible. Sharp look, too. I reckon you could wear this in battle and then wear it to court.&quot; —Lyhr, Facet of Logic
        ///
        ///&quot;Clean the blood off first.&quot; —Lyhr, Facet of Emotion.
        /// </summary>
        internal static string _101535 {
            get {
                return ResourceManager.GetString(":101535", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Impressive materials. Strong, flexible. Sharp look, too. I reckon you could wear this in battle and then wear it to court.&quot; —Lyhr, Facet of Logic
        ///
        ///&quot;Clean the blood off first.&quot; —Lyhr, Facet of Emotion.
        /// </summary>
        internal static string _101536 {
            get {
                return ResourceManager.GetString(":101536", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Feels nigh impenetrable. But I reckon the look of this alone will send most of your enemies running.&quot; —Lyhr, Facet of Logic
        ///
        ///&quot;Those who don&apos;t run&apos;ll just bounce off, eh?&quot; —Lyhr, Facet of Emotion.
        /// </summary>
        internal static string _101544 {
            get {
                return ResourceManager.GetString(":101544", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Feels nigh impenetrable. But I reckon the look of this alone will send most of your enemies running.&quot; —Lyhr, Facet of Logic
        ///
        ///&quot;Those who don&apos;t run&apos;ll just bounce off, eh?&quot; —Lyhr, Facet of Emotion.
        /// </summary>
        internal static string _101551 {
            get {
                return ResourceManager.GetString(":101551", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Flawless blend of leathers and textiles with well-placed hardened armor pieces allowing for rapid movement with ample protection.&quot; —Lyhr, Facet of Logic
        ///
        ///&quot;Aye. Looks sinister, too. In a good way.&quot; —Lyhr, Facet of Emotion.
        /// </summary>
        internal static string _101556 {
            get {
                return ResourceManager.GetString(":101556", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Feels nigh impenetrable. But I reckon the look of this alone will send most of your enemies running.&quot; —Lyhr, Facet of Logic
        ///
        ///&quot;Those who don&apos;t run&apos;ll just bounce off, eh?&quot; —Lyhr, Facet of Emotion.
        /// </summary>
        internal static string _101568 {
            get {
                return ResourceManager.GetString(":101568", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Flawless blend of leathers and textiles with well-placed hardened armor pieces allowing for rapid movement with ample protection.&quot; —Lyhr, Facet of Logic
        ///
        ///&quot;Aye. Looks sinister, too. In a good way.&quot; —Lyhr, Facet of Emotion.
        /// </summary>
        internal static string _101570 {
            get {
                return ResourceManager.GetString(":101570", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Flawless blend of leathers and textiles with well-placed hardened armor pieces allowing for rapid movement with ample protection.&quot; —Lyhr, Facet of Logic
        ///
        ///&quot;Aye. Looks sinister, too. In a good way.&quot; —Lyhr, Facet of Emotion.
        /// </summary>
        internal static string _101579 {
            get {
                return ResourceManager.GetString(":101579", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Mmm... This relic is compact. Extremely versatile as well. Should these find their way into too many hands, I will be looking for a new line of business.&quot;—Archivist Ikur.
        /// </summary>
        internal static string _101582 {
            get {
                return ResourceManager.GetString(":101582", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Flawless blend of leathers and textiles with well-placed hardened armor pieces allowing for rapid movement with ample protection.&quot; —Lyhr, Facet of Logic
        ///
        ///&quot;Aye. Looks sinister, too. In a good way.&quot; —Lyhr, Facet of Emotion.
        /// </summary>
        internal static string _101602 {
            get {
                return ResourceManager.GetString(":101602", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Feels nigh impenetrable. But I reckon the look of this alone will send most of your enemies running.&quot; —Lyhr, Facet of Logic
        ///
        ///&quot;Those who don&apos;t run&apos;ll just bounce off, eh?&quot; —Lyhr, Facet of Emotion.
        /// </summary>
        internal static string _101609 {
            get {
                return ResourceManager.GetString(":101609", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Flawless blend of leathers and textiles with well-placed hardened armor pieces allowing for rapid movement with ample protection.&quot; —Lyhr, Facet of Logic
        ///
        ///&quot;Aye. Looks sinister, too. In a good way.&quot; —Lyhr, Facet of Emotion.
        /// </summary>
        internal static string _101614 {
            get {
                return ResourceManager.GetString(":101614", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Flawless blend of leathers and textiles with well-placed hardened armor pieces allowing for rapid movement with ample protection.&quot; —Lyhr, Facet of Logic
        ///
        ///&quot;Aye. Looks sinister, too. In a good way.&quot; —Lyhr, Facet of Emotion.
        /// </summary>
        internal static string _101645 {
            get {
                return ResourceManager.GetString(":101645", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As The Dragonstorm raged outside, Southward Claw looked over his people. Kodan were huddled together for warmth-their bellies rumbled, and worry laced their eyes. But the wind was too fierce and the falling snow too thick to hunt. He looked at shivering cubs and made his choice: the Claw would lead them south, away from danger. He could wait for Waiting Sorrow no longer..
        /// </summary>
        internal static string _103815 {
            get {
                return ResourceManager.GetString(":103815", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A mysterious pair of gloves that seek to hold the very essence of the worlds between. Open your hands, and harness the energies of a deteriorating fractal to bring that destruction to your foes..
        /// </summary>
        internal static string _105171 {
            get {
                return ResourceManager.GetString(":105171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A mysterious pair of gloves that seek to hold the very essence of the worlds between. Open your hands, and harness the energies of a deteriorating fractal to bring that destruction to your foes..
        /// </summary>
        internal static string _105293 {
            get {
                return ResourceManager.GetString(":105293", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A mysterious pair of gloves that seek to hold the very essence of the worlds between. Open your hands, and harness the energies of a deteriorating fractal to bring that destruction to your foes..
        /// </summary>
        internal static string _105317 {
            get {
                return ResourceManager.GetString(":105317", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hlif traveled to the Far Shiverpeaks to challenge Jormag. Near death, she took one last swing at her foe before falling unconscious. She awoke the next morning—her axe encased in an icy dragon&apos;s head..
        /// </summary>
        internal static string _30684 {
            get {
                return ResourceManager.GetString(":30684", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Secondborn Lonicera sacrificed herself to protect the Pale Tree, a small root sprung from the ground where she breathed her final breath. That root took the shape of a mighty bow..
        /// </summary>
        internal static string _30685 {
            get {
                return ResourceManager.GetString(":30685", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dreamer is as mystifying as it is perplexing, for such a creature doesn&apos;t exist within the known world. It is quite popular among the Skritt, though, who idolize its colorful...prowess..
        /// </summary>
        internal static string _30686 {
            get {
                return ResourceManager.GetString(":30686", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;I know this isn&apos;t the path you&apos;d have chosen for yourself — but the Flame Legion isn&apos;t just your home now; It is my gift to you. Keep this dagger close and never forget who you are: Nonius Ragesinger.&quot;.
        /// </summary>
        internal static string _30687 {
            get {
                return ResourceManager.GetString(":30687", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Minstrel is a bard&apos;s dearest companion, a vessel of their spirit and artistry. Delicate notes fade in the wielder&apos;s wake, leaving passersby with a gentle whisper of their vestige..
        /// </summary>
        internal static string _30688 {
            get {
                return ResourceManager.GetString(":30688", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Although the Six Human Gods have abandoned Tyria, their gifts remain. The oceans and land. The verdant forests, the limitless cosmos beyond—the ultimate love letter to the living, but also a solemn good-bye..
        /// </summary>
        internal static string _30689 {
            get {
                return ResourceManager.GetString(":30689", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A relic dating back to the age of the Great Giant, the Juggernaut may be a gift from the gods. When held by a worthy champion, they are cast in a solid sheet of quicksilver..
        /// </summary>
        internal static string _30690 {
            get {
                return ResourceManager.GetString(":30690", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A historian once wrote of a great beast that lurked off the coast of Orr—possibly a living Champion of Zhaitan. Although she hasn&apos;t been seen for a century past, her kin still roam the dark waters..
        /// </summary>
        internal static string _30691 {
            get {
                return ResourceManager.GetString(":30691", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dare this historian say, the Moot should only be brandished by the most charismatic of warriors. When drawn, your foe may be blinded by its grandiose display of light and splendor..
        /// </summary>
        internal static string _30692 {
            get {
                return ResourceManager.GetString(":30692", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most renowned Thief in Kryta had a couple of calling cards—drove the Lionguard mad. She always left two things behind: a trail of confetti and a note that read &quot;I can run faster than a Centaur!&quot;.
        /// </summary>
        internal static string _30693 {
            get {
                return ResourceManager.GetString(":30693", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast in the likeness of Forge Ironstrike, this rifle was crafted as a tribute to his battle against the Flame Legion Imperator. When Kalla fell in the Plains of Golghein, Ironstrike silenced the traitor..
        /// </summary>
        internal static string _30694 {
            get {
                return ResourceManager.GetString(":30694", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meteorlogicus was designed by a Sylvari astrologer, Surya — a love letter to the sky. She once used the orrery to trace a thunderous cloud that lurked on the horizon. She knew then: a dragon had awoken..
        /// </summary>
        internal static string _30695 {
            get {
                return ResourceManager.GetString(":30695", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The Flameseeker Prophecies&quot; is an ancient tome containing near-complete proclamations of the future as foreseen by the dragon Glint. The final chapter is intentionally left unwritten....
        /// </summary>
        internal static string _30696 {
            get {
                return ResourceManager.GetString(":30696", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Although the vast, impenetrable Unending Ocean has been left unexplored for a century past, fishermen lingering just outside the expanse often catch glimpses of something magnificent..
        /// </summary>
        internal static string _30697 {
            get {
                return ResourceManager.GetString(":30697", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casters and archivists alike worship the iridescent glow that the Bifrost emits. Although the source of its magic is unknown, its luminous aura may hint of realms bygone—tucked away in The Mists..
        /// </summary>
        internal static string _30698 {
            get {
                return ResourceManager.GetString(":30698", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interwoven with an impression of a Dragon whose name Tyria has yet to learn, Bolt is imbued with the strength of a storm–swelling inside like a thunderous inferno, eager to aid its wielder in combat..
        /// </summary>
        internal static string _30699 {
            get {
                return ResourceManager.GetString(":30699", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Cutha woke, he was greeted by sounds of panic and flame. He ran to the window just in time to witness a Dragon perch on a nearby rooftop. &quot;Rodgort,&quot; they whispered. &quot;Rodgort is my name.&quot;.
        /// </summary>
        internal static string _30700 {
            get {
                return ResourceManager.GetString(":30700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;I&apos;ve studied the Krait for some time, but never have I seen anything else quite like that. One of their shamans performed a ritual on one of their dead—undeniably dead—and it was living once again!&quot;.
        /// </summary>
        internal static string _30701 {
            get {
                return ResourceManager.GetString(":30701", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Norn ballad recounts a quarrel between the Great Wolf and a serpent who sought to become a Spirit of the Wild: O little snake, do you have what it takes? Howl, howl—open the gate..
        /// </summary>
        internal static string _30702 {
            get {
                return ResourceManager.GetString(":30702", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is said that when Dwayna woke each morning, she gifted her followers with the warmth of dawn. All of the creatures in Tyria stirred from their slumber to witness the glorious sunrise..
        /// </summary>
        internal static string _30703 {
            get {
                return ResourceManager.GetString(":30703", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While the other gods slept, Grenth took up his throne—beckoning his companions to dance and howl beneath the stars. It was said that his powers were most potent when the moon was highest in the sky..
        /// </summary>
        internal static string _30704 {
            get {
                return ResourceManager.GetString(":30704", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nevermore is a living reminder that there&apos;s always a purpose to Raven (Spirit of the Wild) riddles and tests. When you&apos;re mired in despair, lost for answers, he pushes because he knows you can fly..
        /// </summary>
        internal static string _71383 {
            get {
                return ResourceManager.GetString(":71383", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Remember: the blue stuff is the Alchemical Catalyst, and the red stuff is the Transcendent Energy. Don&apos;t drink either of them. And whatever you do, don&apos;t drop this thing.&quot;.
        /// </summary>
        internal static string _72713 {
            get {
                return ResourceManager.GetString(":72713", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log 18204: Losing transmissions̱omething went wrongI̱&apos;mstranded_. I&apos;m stuck inFractal. Floating. The whole island isf̲loating. Call themselvesForgotten. Trees. I sees̱omeone_? Can you hearme?.
        /// </summary>
        internal static string _74155 {
            get {
                return ResourceManager.GetString(":74155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunsmith Ouissal dreamed she gifted an exquisite axe to a woman with skin like the star-kissed sky above the Astralarium. She woke and ran to her workbench, a delighted laugh lingering in her memory..
        /// </summary>
        internal static string _76158 {
            get {
                return ResourceManager.GetString(":76158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A handful of warriors know what it&apos;s like to bask in the effervescent glow of a fresh victory—sweat dripping from their brow, voice raw. Only the bravest ascend to such glory..
        /// </summary>
        internal static string _77474 {
            get {
                return ResourceManager.GetString(":77474", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks to their bond with you, someday Nola, Halkor, and Brill will be magnificent tigers, facing the world with dignity and wisdom. For now, their paws are far too big for them..
        /// </summary>
        internal static string _78556 {
            get {
                return ResourceManager.GetString(":78556", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eureka was the pride and downfall of a rogue Priory research team who set out to reactivate Obsidian Shard sampled from ancient armor. Paired with magitech, the material assumed a deadlier form..
        /// </summary>
        internal static string _79562 {
            get {
                return ResourceManager.GetString(":79562", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tiny Quaggan Shooshadoo has made up their mind to follow in your footsteps as a champion of Tyria. You&apos;ll need to carry them until their stride is a bit longer..
        /// </summary>
        internal static string _79802 {
            get {
                return ResourceManager.GetString(":79802", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These vestments are imbued with the power of a crystalline heart, once carried through an abandoned prison to its final resting place. It is exemplary of the wearer&apos;s tenacity in the face of darkness..
        /// </summary>
        internal static string _80111 {
            get {
                return ResourceManager.GetString(":80111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These vestments are imbued with the power of a crystalline heart, once carried through an abandoned prison to its final resting place. It is exemplary of the wearer&apos;s tenacity in the face of darkness..
        /// </summary>
        internal static string _80131 {
            get {
                return ResourceManager.GetString(":80131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A symbol of cunning and patience, this garb carries power siphoned from a mysterious beast guarding the Forsaken Thicket. They seem to pulsate, albeit gently, when nearing a ley line..
        /// </summary>
        internal static string _80145 {
            get {
                return ResourceManager.GetString(":80145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A symbol of cunning and patience, this garb carries power siphoned from a mysterious beast guarding the Forsaken Thicket. They seem to pulsate, albeit gently, when nearing a ley line..
        /// </summary>
        internal static string _80161 {
            get {
                return ResourceManager.GetString(":80161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These vestments are imbued with the power of a crystalline heart, once carried through an abandoned prison to its final resting place. It is exemplary of the wearer&apos;s tenacity in the face of darkness..
        /// </summary>
        internal static string _80190 {
            get {
                return ResourceManager.GetString(":80190", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This armor is worn only by those who helped defeat Xera and silence the White Mantle in the depths of the Forsaken Thicket. When it catches the sun just right, it is a beacon of hope in a cruel world..
        /// </summary>
        internal static string _80205 {
            get {
                return ResourceManager.GetString(":80205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These vestments are imbued with the power of a crystalline heart, once carried through an abandoned prison to its final resting place. It is exemplary of the wearer&apos;s tenacity in the face of darkness..
        /// </summary>
        internal static string _80248 {
            get {
                return ResourceManager.GetString(":80248", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A symbol of cunning and patience, this garb carries power siphoned from a mysterious beast guarding the Forsaken Thicket. They seem to pulsate, albeit gently, when nearing a ley line..
        /// </summary>
        internal static string _80252 {
            get {
                return ResourceManager.GetString(":80252", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This armor is worn only by those who helped defeat Xera and silence the White Mantle in the depths of the Forsaken Thicket. When it catches the sun just right, it is a beacon of hope in a cruel world..
        /// </summary>
        internal static string _80254 {
            get {
                return ResourceManager.GetString(":80254", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This armor is worn only by those who helped defeat Xera and silence the White Mantle in the depths of the Forsaken Thicket. When it catches the sun just right, it is a beacon of hope in a cruel world..
        /// </summary>
        internal static string _80277 {
            get {
                return ResourceManager.GetString(":80277", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A symbol of cunning and patience, this garb carries power siphoned from a mysterious beast guarding the Forsaken Thicket. They seem to pulsate, albeit gently, when nearing a ley line..
        /// </summary>
        internal static string _80281 {
            get {
                return ResourceManager.GetString(":80281", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A symbol of cunning and patience, this garb carries power siphoned from a mysterious beast guarding the Forsaken Thicket. They seem to pulsate, albeit gently, when nearing a ley line..
        /// </summary>
        internal static string _80296 {
            get {
                return ResourceManager.GetString(":80296", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These vestments are imbued with the power of a crystalline heart, once carried through an abandoned prison to its final resting place. It is exemplary of the wearer&apos;s tenacity in the face of darkness..
        /// </summary>
        internal static string _80356 {
            get {
                return ResourceManager.GetString(":80356", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This armor is worn only by those who helped defeat Xera and silence the White Mantle in the depths of the Forsaken Thicket. When it catches the sun just right, it is a beacon of hope in a cruel world..
        /// </summary>
        internal static string _80384 {
            get {
                return ResourceManager.GetString(":80384", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These vestments are imbued with the power of a crystalline heart, once carried through an abandoned prison to its final resting place. It is exemplary of the wearer&apos;s tenacity in the face of darkness..
        /// </summary>
        internal static string _80399 {
            get {
                return ResourceManager.GetString(":80399", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This armor is worn only by those who helped defeat Xera and silence the White Mantle in the depths of the Forsaken Thicket. When it catches the sun just right, it is a beacon of hope in a cruel world..
        /// </summary>
        internal static string _80435 {
            get {
                return ResourceManager.GetString(":80435", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As Zhaitan&apos;s influence grew, the Vigil raced to the site of Kryta&apos;s greatest maritime tragedy on an improbable mission. The HMS Divinity&apos;s long-dead crew—shackled to their ship as it sank—were all recovered..
        /// </summary>
        internal static string _80488 {
            get {
                return ResourceManager.GetString(":80488", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This armor is worn only by those who helped defeat Xera and silence the White Mantle in the depths of the Forsaken Thicket. When it catches the sun just right, it is a beacon of hope in a cruel world..
        /// </summary>
        internal static string _80557 {
            get {
                return ResourceManager.GetString(":80557", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A symbol of cunning and patience, this garb carries power siphoned from a mysterious beast guarding the Forsaken Thicket. They seem to pulsate, albeit gently, when nearing a ley line..
        /// </summary>
        internal static string _80578 {
            get {
                return ResourceManager.GetString(":80578", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In lieu of written records, some temples of Balthazar kept elaborate weapons depicting the rituals they were used in. Few survived Balthazar&apos;s fall, and many were immolated by his loyalist priests..
        /// </summary>
        internal static string _81206 {
            get {
                return ResourceManager.GetString(":81206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warbringer is made from the salvaged remnants of enemies fallen, emblazoned with swords and spears pulled from still-warm corpses. It is a reminder of battles won and lost—whispers of victory..
        /// </summary>
        internal static string _81462 {
            get {
                return ResourceManager.GetString(":81462", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharur was retrieved from among the spectral weapons guarding the Source of Orr. Though its lingering corruption is aimless and benign, not even the Artesian Waters could fully cleanse it..
        /// </summary>
        internal static string _81839 {
            get {
                return ResourceManager.GetString(":81839", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Mordremoth&apos;s power seeped into the earth, some sought to harness it, control it - bringing forth new dangers. Heroes faced those enemies head on with a spark of bravery and a warrior&apos;s might..
        /// </summary>
        internal static string _81908 {
            get {
                return ResourceManager.GetString(":81908", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To its namesake faction, the Shining Blade is more an old friend than an ancient Seer artifact. Its historical codenames include &quot;the family heirloom,&quot; &quot;that old thing,&quot; and &quot;Gran&apos;s best knife.&quot;.
        /// </summary>
        internal static string _81957 {
            get {
                return ResourceManager.GetString(":81957", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Are we dancing or dueling? It&apos;s your turn to pick.&quot;.
        /// </summary>
        internal static string _82093 {
            get {
                return ResourceManager.GetString(":82093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lore of this Item has been obscured by the Mists..
        /// </summary>
        internal static string _82098 {
            get {
                return ResourceManager.GetString(":82098", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;This sturdy adventuring suit glows with Mist energy. When you wear it inside Obsidian Sanctum, sometimes you catch yourself longing for a forbidden reunion.&quot;.
        /// </summary>
        internal static string _82102 {
            get {
                return ResourceManager.GetString(":82102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This exquisite scholarly garb shimmers with The Mists energy. When you wear it through Ruins of Power and unguarded Keep, sometimes you&apos;re haunted by nostalgia..
        /// </summary>
        internal static string _82109 {
            get {
                return ResourceManager.GetString(":82109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;They never come back whole. Maybe they&apos;re only half-remembered...&quot;.
        /// </summary>
        internal static string _82173 {
            get {
                return ResourceManager.GetString(":82173", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;This sturdy adventuring suit glows with Mist energy. When you wear it inside Obsidian Sanctum, sometimes you catch yourself longing for a forbidden reunion.&quot;.
        /// </summary>
        internal static string _82180 {
            get {
                return ResourceManager.GetString(":82180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;This—right now—is the rest of your life. Live it well.&quot;.
        /// </summary>
        internal static string _82196 {
            get {
                return ResourceManager.GetString(":82196", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This garb is the perfect blend of lightweight and sturdy, ideal for the sneakiest saboteur. Their enemies may cry foul play, but I assure you, only those with a swift foot possess such finery..
        /// </summary>
        internal static string _82214 {
            get {
                return ResourceManager.GetString(":82214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This garb is the perfect blend of lightweight and sturdy, ideal for the sneakiest saboteur. Their enemies may cry foul play, but I assure you, only those with a swift foot possess such finery..
        /// </summary>
        internal static string _82245 {
            get {
                return ResourceManager.GetString(":82245", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lore of this Item has been obscured by the Mists..
        /// </summary>
        internal static string _82268 {
            get {
                return ResourceManager.GetString(":82268", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lore of this Item has been obscured by the Mists..
        /// </summary>
        internal static string _82272 {
            get {
                return ResourceManager.GetString(":82272", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lore of this Item has been obscured by the Mists..
        /// </summary>
        internal static string _82334 {
            get {
                return ResourceManager.GetString(":82334", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This powerful soldier&apos;s armor pulses with The Mists energy. When you wear it on the upper floor of Stonemist Castle, sometimes your chest aches with pride and agony..
        /// </summary>
        internal static string _82348 {
            get {
                return ResourceManager.GetString(":82348", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lore of this Item has been obscured by the Mists..
        /// </summary>
        internal static string _82401 {
            get {
                return ResourceManager.GetString(":82401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lore of this Item has been obscured by the Mists..
        /// </summary>
        internal static string _82410 {
            get {
                return ResourceManager.GetString(":82410", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lore of this Item has been obscured by the Mists..
        /// </summary>
        internal static string _82423 {
            get {
                return ResourceManager.GetString(":82423", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Are we dancing or dueling? It&apos;s your turn to pick.&quot;.
        /// </summary>
        internal static string _82437 {
            get {
                return ResourceManager.GetString(":82437", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;This—right now—is the rest of your life. Live it well.&quot;.
        /// </summary>
        internal static string _82456 {
            get {
                return ResourceManager.GetString(":82456", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This suit of armor is melded from the helms of the wearer&apos;s opponents, a reminder of the battles won. There&apos;s something bittersweet about the way it smells - like clashing swords and sweaty palms..
        /// </summary>
        internal static string _82465 {
            get {
                return ResourceManager.GetString(":82465", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This exquisite scholarly garb shimmers with The Mists energy. When you wear it through Ruins of Power and unguarded Keep, sometimes you&apos;re haunted by nostalgia..
        /// </summary>
        internal static string _82502 {
            get {
                return ResourceManager.GetString(":82502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This garb is the perfect blend of lightweight and sturdy, ideal for the sneakiest saboteur. Their enemies may cry foul play, but I assure you, only those with a swift foot possess such finery..
        /// </summary>
        internal static string _82512 {
            get {
                return ResourceManager.GetString(":82512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crafted from the finest silks, these vestments are a symbol not only of sheer strength but also quick-witted bravery and grit. They know their way around the streets of Battle of Khylo here and back again..
        /// </summary>
        internal static string _82519 {
            get {
                return ResourceManager.GetString(":82519", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;This sturdy adventuring suit glows with Mist energy. When you wear it inside Obsidian Sanctum, sometimes you catch yourself longing for a forbidden reunion.&quot;.
        /// </summary>
        internal static string _82552 {
            get {
                return ResourceManager.GetString(":82552", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This garb is the perfect blend of lightweight and sturdy, ideal for the sneakiest saboteur. Their enemies may cry foul play, but I assure you, only those with a swift foot possess such finery..
        /// </summary>
        internal static string _82670 {
            get {
                return ResourceManager.GetString(":82670", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lore of this Item has been obscured by the Mists..
        /// </summary>
        internal static string _82698 {
            get {
                return ResourceManager.GetString(":82698", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;This—right now—is the rest of your life. Live it well.&quot;.
        /// </summary>
        internal static string _82801 {
            get {
                return ResourceManager.GetString(":82801", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;They never come back whole. Maybe they&apos;re only half-remembered...&quot;.
        /// </summary>
        internal static string _82902 {
            get {
                return ResourceManager.GetString(":82902", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Are we dancing or dueling? It&apos;s your turn to pick.&quot;.
        /// </summary>
        internal static string _82903 {
            get {
                return ResourceManager.GetString(":82903", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This exquisite scholarly garb shimmers with The Mists energy. When you wear it through Ruins of Power and unguarded Keep, sometimes you&apos;re haunted by nostalgia..
        /// </summary>
        internal static string _82925 {
            get {
                return ResourceManager.GetString(":82925", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;This—right now—is the rest of your life. Live it well.&quot;.
        /// </summary>
        internal static string _82963 {
            get {
                return ResourceManager.GetString(":82963", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Are we dancing or dueling? It&apos;s your turn to pick.&quot;.
        /// </summary>
        internal static string _82994 {
            get {
                return ResourceManager.GetString(":82994", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;They never come back whole. Maybe they&apos;re only half-remembered...&quot;.
        /// </summary>
        internal static string _83036 {
            get {
                return ResourceManager.GetString(":83036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;This sturdy adventuring suit glows with Mist energy. When you wear it inside Obsidian Sanctum, sometimes you catch yourself longing for a forbidden reunion.&quot;.
        /// </summary>
        internal static string _83087 {
            get {
                return ResourceManager.GetString(":83087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This powerful soldier&apos;s armor pulses with The Mists energy. When you wear it on the upper floor of Stonemist Castle, sometimes your chest aches with pride and agony..
        /// </summary>
        internal static string _83094 {
            get {
                return ResourceManager.GetString(":83094", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crafted from the finest silks, these vestments are a symbol not only of sheer strength but also quick-witted bravery and grit. They know their way around the streets of Battle of Khylo here and back again..
        /// </summary>
        internal static string _83113 {
            get {
                return ResourceManager.GetString(":83113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This suit of armor is melded from the helms of the wearer&apos;s opponents, a reminder of the battles won. There&apos;s something bittersweet about the way it smells - like clashing swords and sweaty palms..
        /// </summary>
        internal static string _83127 {
            get {
                return ResourceManager.GetString(":83127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crafted from the finest silks, these vestments are a symbol not only of sheer strength but also quick-witted bravery and grit. They know their way around the streets of Battle of Khylo here and back again..
        /// </summary>
        internal static string _83162 {
            get {
                return ResourceManager.GetString(":83162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lore of this Item has been obscured by the Mists..
        /// </summary>
        internal static string _83240 {
            get {
                return ResourceManager.GetString(":83240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;They never come back whole. Maybe they&apos;re only half-remembered...&quot;.
        /// </summary>
        internal static string _83289 {
            get {
                return ResourceManager.GetString(":83289", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This exquisite scholarly garb shimmers with The Mists energy. When you wear it through Ruins of Power and unguarded Keep, sometimes you&apos;re haunted by nostalgia..
        /// </summary>
        internal static string _83308 {
            get {
                return ResourceManager.GetString(":83308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This suit of armor is melded from the helms of the wearer&apos;s opponents, a reminder of the battles won. There&apos;s something bittersweet about the way it smells - like clashing swords and sweaty palms..
        /// </summary>
        internal static string _83323 {
            get {
                return ResourceManager.GetString(":83323", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This suit of armor is melded from the helms of the wearer&apos;s opponents, a reminder of the battles won. There&apos;s something bittersweet about the way it smells - like clashing swords and sweaty palms..
        /// </summary>
        internal static string _83348 {
            get {
                return ResourceManager.GetString(":83348", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;This—right now—is the rest of your life. Live it well.&quot;.
        /// </summary>
        internal static string _83394 {
            get {
                return ResourceManager.GetString(":83394", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This exquisite scholarly garb shimmers with The Mists energy. When you wear it through Ruins of Power and unguarded Keep, sometimes you&apos;re haunted by nostalgia..
        /// </summary>
        internal static string _83482 {
            get {
                return ResourceManager.GetString(":83482", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;They never come back whole. Maybe they&apos;re only half-remembered...&quot;.
        /// </summary>
        internal static string _83497 {
            get {
                return ResourceManager.GetString(":83497", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crafted from the finest silks, these vestments are a symbol not only of sheer strength but also quick-witted bravery and grit. They know their way around the streets of Battle of Khylo here and back again..
        /// </summary>
        internal static string _83595 {
            get {
                return ResourceManager.GetString(":83595", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lore of this Item has been obscured by the Mists..
        /// </summary>
        internal static string _83676 {
            get {
                return ResourceManager.GetString(":83676", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;This sturdy adventuring suit glows with Mist energy. When you wear it inside Obsidian Sanctum, sometimes you catch yourself longing for a forbidden reunion.&quot;.
        /// </summary>
        internal static string _83699 {
            get {
                return ResourceManager.GetString(":83699", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This powerful soldier&apos;s armor pulses with The Mists energy. When you wear it on the upper floor of Stonemist Castle, sometimes your chest aches with pride and agony..
        /// </summary>
        internal static string _83702 {
            get {
                return ResourceManager.GetString(":83702", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lore of this Item has been obscured by the Mists..
        /// </summary>
        internal static string _83729 {
            get {
                return ResourceManager.GetString(":83729", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;This sturdy adventuring suit glows with Mist energy. When you wear it inside Obsidian Sanctum, sometimes you catch yourself longing for a forbidden reunion.&quot;.
        /// </summary>
        internal static string _83862 {
            get {
                return ResourceManager.GetString(":83862", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This suit of armor is melded from the helms of the wearer&apos;s opponents, a reminder of the battles won. There&apos;s something bittersweet about the way it smells - like clashing swords and sweaty palms..
        /// </summary>
        internal static string _83921 {
            get {
                return ResourceManager.GetString(":83921", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This garb is the perfect blend of lightweight and sturdy, ideal for the sneakiest saboteur. Their enemies may cry foul play, but I assure you, only those with a swift foot possess such finery..
        /// </summary>
        internal static string _83929 {
            get {
                return ResourceManager.GetString(":83929", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lore of this Item has been obscured by the Mists..
        /// </summary>
        internal static string _83957 {
            get {
                return ResourceManager.GetString(":83957", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Are we dancing or dueling? It&apos;s your turn to pick.&quot;.
        /// </summary>
        internal static string _84110 {
            get {
                return ResourceManager.GetString(":84110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;This—right now—is the rest of your life. Live it well.&quot;.
        /// </summary>
        internal static string _84176 {
            get {
                return ResourceManager.GetString(":84176", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This powerful soldier&apos;s armor pulses with The Mists energy. When you wear it on the upper floor of Stonemist Castle, sometimes your chest aches with pride and agony..
        /// </summary>
        internal static string _84181 {
            get {
                return ResourceManager.GetString(":84181", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This powerful soldier&apos;s armor pulses with The Mists energy. When you wear it on the upper floor of Stonemist Castle, sometimes your chest aches with pride and agony..
        /// </summary>
        internal static string _84301 {
            get {
                return ResourceManager.GetString(":84301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lore of this Item has been obscured by the Mists..
        /// </summary>
        internal static string _84341 {
            get {
                return ResourceManager.GetString(":84341", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lore of this Item has been obscured by the Mists..
        /// </summary>
        internal static string _84427 {
            get {
                return ResourceManager.GetString(":84427", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lore of this Item has been obscured by the Mists..
        /// </summary>
        internal static string _84461 {
            get {
                return ResourceManager.GetString(":84461", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This powerful soldier&apos;s armor pulses with The Mists energy. When you wear it on the upper floor of Stonemist Castle, sometimes your chest aches with pride and agony..
        /// </summary>
        internal static string _84481 {
            get {
                return ResourceManager.GetString(":84481", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This exquisite scholarly garb shimmers with The Mists energy. When you wear it through Ruins of Power and unguarded Keep, sometimes you&apos;re haunted by nostalgia..
        /// </summary>
        internal static string _84508 {
            get {
                return ResourceManager.GetString(":84508", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crafted from the finest silks, these vestments are a symbol not only of sheer strength but also quick-witted bravery and grit. They know their way around the streets of Battle of Khylo here and back again..
        /// </summary>
        internal static string _84546 {
            get {
                return ResourceManager.GetString(":84546", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lore of this Item has been obscured by the Mists..
        /// </summary>
        internal static string _84561 {
            get {
                return ResourceManager.GetString(":84561", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Are we dancing or dueling? It&apos;s your turn to pick.&quot;.
        /// </summary>
        internal static string _84578 {
            get {
                return ResourceManager.GetString(":84578", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;They never come back whole. Maybe they&apos;re only half-remembered...&quot;.
        /// </summary>
        internal static string _84629 {
            get {
                return ResourceManager.GetString(":84629", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crafted from the finest silks, these vestments are a symbol not only of sheer strength but also quick-witted bravery and grit. They know their way around the streets of Battle of Khylo here and back again..
        /// </summary>
        internal static string _84633 {
            get {
                return ResourceManager.GetString(":84633", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This garb is the perfect blend of lightweight and sturdy, ideal for the sneakiest saboteur. Their enemies may cry foul play, but I assure you, only those with a swift foot possess such finery..
        /// </summary>
        internal static string _84643 {
            get {
                return ResourceManager.GetString(":84643", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This suit of armor is melded from the helms of the wearer&apos;s opponents, a reminder of the battles won. There&apos;s something bittersweet about the way it smells - like clashing swords and sweaty palms..
        /// </summary>
        internal static string _84655 {
            get {
                return ResourceManager.GetString(":84655", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lore of this Item has been obscured by the Mists..
        /// </summary>
        internal static string _84723 {
            get {
                return ResourceManager.GetString(":84723", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lore of this Item has been obscured by the Mists..
        /// </summary>
        internal static string _84748 {
            get {
                return ResourceManager.GetString(":84748", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Binding of Ipos is as mystifying as it is venomous, dripping with ancient knowledge. Any warrior brave enough to carry this tome will be gifted with millennia of sinister magics..
        /// </summary>
        internal static string _86098 {
            get {
                return ResourceManager.GetString(":86098", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ancient charr relic has served as an apparatus of revolution, a key to power, and a symbol of stability. The Claw of the Khan-Ur is reforged with every great feat its wielders accomplish..
        /// </summary>
        internal static string _87109 {
            get {
                return ResourceManager.GetString(":87109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Grenth&apos;s powers were raw and new, he crafted a weapon more sinister than he intended. Verdarach summons victims of horrific battles as vengeful wraiths, eager to conscript the newly slain..
        /// </summary>
        internal static string _87687 {
            get {
                return ResourceManager.GetString(":87687", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hylek of the Astrozintli Forelands revere the life serpent Xiuquatl. While it&apos;s too small and gentle to be their savior, those traits make it Tequatl the Sunless perfect opposite—and a potent symbol of hope..
        /// </summary>
        internal static string _88576 {
            get {
                return ResourceManager.GetString(":88576", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They needed to hold out a little longer—buy enough time for their partner to gain control of the cannon. They knew this dance all too well, and it was always exhilarating..
        /// </summary>
        internal static string _89093 {
            get {
                return ResourceManager.GetString(":89093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lore of this Item has been obscured by the Mists..
        /// </summary>
        internal static string _89094 {
            get {
                return ResourceManager.GetString(":89094", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lore of this Item has been obscured by the Mists..
        /// </summary>
        internal static string _89101 {
            get {
                return ResourceManager.GetString(":89101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They needed to hold out a little longer—buy enough time for their partner to gain control of the cannon. They knew this dance all too well, and it was always exhilarating..
        /// </summary>
        internal static string _89117 {
            get {
                return ResourceManager.GetString(":89117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lore of this Item has been obscured by the Mists..
        /// </summary>
        internal static string _89126 {
            get {
                return ResourceManager.GetString(":89126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lore of this Item has been obscured by the Mists..
        /// </summary>
        internal static string _89134 {
            get {
                return ResourceManager.GetString(":89134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They needed to hold out a little longer—buy enough time for their partner to gain control of the cannon. They knew this dance all too well, and it was always exhilarating..
        /// </summary>
        internal static string _89152 {
            get {
                return ResourceManager.GetString(":89152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lore of this Item has been obscured by the Mists..
        /// </summary>
        internal static string _89158 {
            get {
                return ResourceManager.GetString(":89158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lore of this Item has been obscured by the Mists..
        /// </summary>
        internal static string _89167 {
            get {
                return ResourceManager.GetString(":89167", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lore of this Item has been obscured by the Mists..
        /// </summary>
        internal static string _89174 {
            get {
                return ResourceManager.GetString(":89174", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lore of this Item has been obscured by the Mists..
        /// </summary>
        internal static string _89183 {
            get {
                return ResourceManager.GetString(":89183", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They needed to hold out a little longer—buy enough time for their partner to gain control of the cannon. They knew this dance all too well, and it was always exhilarating..
        /// </summary>
        internal static string _89209 {
            get {
                return ResourceManager.GetString(":89209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lore of this Item has been obscured by the Mists..
        /// </summary>
        internal static string _89234 {
            get {
                return ResourceManager.GetString(":89234", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lore of this Item has been obscured by the Mists..
        /// </summary>
        internal static string _89235 {
            get {
                return ResourceManager.GetString(":89235", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lore of this Item has been obscured by the Mists..
        /// </summary>
        internal static string _89245 {
            get {
                return ResourceManager.GetString(":89245", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They needed to hold out a little longer—buy enough time for their partner to gain control of the cannon. They knew this dance all too well, and it was always exhilarating..
        /// </summary>
        internal static string _89252 {
            get {
                return ResourceManager.GetString(":89252", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lore of this Item has been obscured by the Mists..
        /// </summary>
        internal static string _89260 {
            get {
                return ResourceManager.GetString(":89260", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They needed to hold out a little longer—buy enough time for their partner to gain control of the cannon. They knew this dance all too well, and it was always exhilarating..
        /// </summary>
        internal static string _89266 {
            get {
                return ResourceManager.GetString(":89266", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scholars discovered Pharus in Siren&apos;s Reef.[wikipedia:sic] All attempts to store and catalog it have failed; if not carried by a hero, it reappears at Dwayna&apos;s Reliquary among the other artifacts..
        /// </summary>
        internal static string _89854 {
            get {
                return ResourceManager.GetString(":89854", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorers venture into The Mists, and sometimes the Mists venture back. Though far less sentient than the Mist-being gw1:Razah, Exordium takes some joy in adapting to its wielder&apos;s needs and expectations..
        /// </summary>
        internal static string _90551 {
            get {
                return ResourceManager.GetString(":90551", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;They killed him. Balthazar. If Lyssa ever learns of this...I don&apos;t know what she&apos;d do—what any of them would do. They still claim benevolence, but let&apos;s hope they weren&apos;t watching too closely.&quot;.
        /// </summary>
        internal static string _91048 {
            get {
                return ResourceManager.GetString(":91048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They walked through the Underworld, dove straight into the Mystic Forge. They crossed through the long-forgotten halls of The Key of Ahdashim—such feats would be cast in gold and told to awe-struck children..
        /// </summary>
        internal static string _91234 {
            get {
                return ResourceManager.GetString(":91234", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;I believe that sigils contain fragments, or memories, from the greatest battles in Tyria (world)&apos;s history,&quot; Lady Nari wrote. &quot;This one may be our only window into the Battle of the Three Queens.&quot;.
        /// </summary>
        internal static string _91505 {
            get {
                return ResourceManager.GetString(":91505", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lady Nari once wrote that runes are imbued with the memories of ancient warriors and that the effects they grant are remnants of their power..
        /// </summary>
        internal static string _91536 {
            get {
                return ResourceManager.GetString(":91536", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amulet was a sight to behold, swinging back and forth while the warrior perfected the swing of her sword. She was a champion—onlookers bowed as they passed, but her attention was elsewhere..
        /// </summary>
        internal static string _92991 {
            get {
                return ResourceManager.GetString(":92991", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ring was fixed on his left hand, a reminder of the battle days before. While they held Stonemist Castle, it could be minutes until their enemy appeared at the front gate. There was no time for mourning..
        /// </summary>
        internal static string _93105 {
            get {
                return ResourceManager.GetString(":93105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pact Commander adventures before we met, and our struggles together—this is the strength from our bond, Aurene Dragon champion..
        /// </summary>
        internal static string _95380 {
            get {
                return ResourceManager.GetString(":95380", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loneliness of this world is terrifying, empty... Who can I confide in now? Can anyone out there hear me...? Do you understand what it&apos;s like to hold such power?.
        /// </summary>
        internal static string _95612 {
            get {
                return ResourceManager.GetString(":95612", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t want to have a destiny. I want to eat half your food and go to sleep while you read, but if I act like a baby now everyone will remember later. Maybe Vlast was right and it&apos;s better if they think I&apos;m angry..
        /// </summary>
        internal static string _95675 {
            get {
                return ResourceManager.GetString(":95675", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Even inside the shell of my Glint&apos;s Egg, I could feel them—Pact Commander. Their soul smelled of pain and ached, but somehow I knew... I knew that I was safe in their care..
        /// </summary>
        internal static string _95684 {
            get {
                return ResourceManager.GetString(":95684", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elder Dragon Soo-Won kept her distance from the mortal realm, but I needed that connection—I yearned for it. Without my Dragon&apos;s Watch, would I feel the same need to protect this place?.
        /// </summary>
        internal static string _95808 {
            get {
                return ResourceManager.GetString(":95808", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taimi doesn&apos;t always understand me, but she helps other people understand me since she can hold a conversation with me by herself. Although...I wouldn&apos;t miss it if she stopped giving me a squeaky voice..
        /// </summary>
        internal static string _96028 {
            get {
                return ResourceManager.GetString(":96028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The weight of the world, the balance of time and nature... All of it, sitting on my shoulders. It&apos;s heavy... Crippling, even. But there&apos;s something comforting, knowing that I can make a difference..
        /// </summary>
        internal static string _96203 {
            get {
                return ResourceManager.GetString(":96203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Vlast&apos;s duty and my Glint&apos;s destiny wouldn&apos;t have existed without my Kralkatorrik&apos;s hunger. If that&apos;s so, isn&apos;t a Prophecies just knowing what must be done and who should do it?.
        /// </summary>
        internal static string _96221 {
            get {
                return ResourceManager.GetString(":96221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to His voice whispers at the back of my mind, his soul as ripe as it was in &quot;life.&quot; He tells me things. About The Mists, about The Underworld... Terrifying, dark things..
        /// </summary>
        internal static string _96356 {
            get {
                return ResourceManager.GetString(":96356", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balthazar make me furious. If you had truly wanted anything but revenge, my champion could have helped you instead of To Kill a God you. You wouldn&apos;t have been alone. I wish I could have talked to you. I wish I believed it could have helped..
        /// </summary>
        internal static string _96652 {
            get {
                return ResourceManager.GetString(":96652", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic. Everywhere. Swirling and whispering, like a flock of birds dancing through the air. It settles at my feet. Dust, piling higher and higher like sand on a beach... Wake up, it says. Wake up..
        /// </summary>
        internal static string _96937 {
            get {
                return ResourceManager.GetString(":96937", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can hear Soo-Won. Her voice lingers at the edge of my mind like a memory I&apos;ve long forgotten—the lightest touch. Bubbling beneath the ocean waves, deep below... Her voice, like a feather against my scales..
        /// </summary>
        internal static string _97077 {
            get {
                return ResourceManager.GetString(":97077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are people who already have too much power the only ones who want it? Why do they think they need more? This can&apos;t be fixed with weapons or magic, it&apos;s just...it&apos;s just adults panicking or having tantrums..
        /// </summary>
        internal static string _97099 {
            get {
                return ResourceManager.GetString(":97099", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I chirped at my Pact Commander—my &quot;Champion.&quot; I could already feel something pulling us together, even Precocious Aurene. Or perhaps it was just a rumble of my belly, recently filled with Smoked Fish Dinner (for Aurene)..
        /// </summary>
        internal static string _97165 {
            get {
                return ResourceManager.GetString(":97165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When I was too little to fly, I dreamed of it. I still dreamed after Vlast The Sacrifice, but the promise of endless freedom and joy wasn&apos;t real anymore. His heart and mind were tethered to the ground, and in the end his body joined them..
        /// </summary>
        internal static string _97377 {
            get {
                return ResourceManager.GetString(":97377", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It wasn&apos;t painful, but it was dark. Darker than anything I&apos;ve seen or felt before. Pulsing with unfamiliar magic... Malice, bleeding into my flesh. Caressing my mind like... Like....
        /// </summary>
        internal static string _97590 {
            get {
                return ResourceManager.GetString(":97590", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should never lose anything or anyone, ever again. The world should be like a beautiful garden and only grow around you forever. I know it can&apos;t happen that way, but I don&apos;t want to be what you lose next..
        /// </summary>
        internal static string _97783 {
            get {
                return ResourceManager.GetString(":97783", resourceCulture);
            }
        }
    }
}
