//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegendaryArmory.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lore {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lore() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LegendaryArmory.Strings.Lore", typeof(Lore).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Feels nigh impenetrable. But I reckon the look of this alone will send most of your enemies running.&quot; —Lyhr, Facet of Logic
        ///
        ///&quot;Those who don&apos;t run&apos;ll just bounce off, eh?&quot; —Lyhr, Facet of Emotion.
        /// </summary>
        internal static string _101521 {
            get {
                return ResourceManager.GetString(":101521", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hlif traveled to the Far Shiverpeaks to challenge Jormag. Near death, she took one last swing at her foe before falling unconscious. She awoke the next morning—her axe encased in an icy dragon&apos;s head..
        /// </summary>
        internal static string _30684 {
            get {
                return ResourceManager.GetString(":30684", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Secondborn Lonicera sacrificed herself to protect the Pale Tree, a small root sprung from the ground where she breathed her final breath. That root took the shape of a mighty bow..
        /// </summary>
        internal static string _30685 {
            get {
                return ResourceManager.GetString(":30685", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dreamer is as mystifying as it is perplexing, for such a creature doesn&apos;t exist within the known world. It is quite popular among the skritt, though, who idolize its colorful...prowess..
        /// </summary>
        internal static string _30686 {
            get {
                return ResourceManager.GetString(":30686", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;I know this isn&apos;t the path you&apos;d have chosen for yourself — but the Flame Legion isn&apos;t just your home now; It is my gift to you. Keep this dagger close and never forget who you are: Nonius Ragesinger.&quot;.
        /// </summary>
        internal static string _30687 {
            get {
                return ResourceManager.GetString(":30687", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Minstrel is a bard&apos;s dearest companion, a vessel of their spirit and artistry. Delicate notes fade in the wielder&apos;s wake, leaving passersby with a gentle whisper of their vestige..
        /// </summary>
        internal static string _30688 {
            get {
                return ResourceManager.GetString(":30688", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Although the gods have abandoned Tyria, their gifts remain. The oceans and land. The verdant forests, the limitless cosmos beyond—the ultimate love letter to the living, but also a solemn good-bye..
        /// </summary>
        internal static string _30689 {
            get {
                return ResourceManager.GetString(":30689", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A relic dating back to the age of the Giganticus Lupicus, the Juggernaut may be a gift from the gods. When held by a worthy champion, they are cast in a solid sheet of quicksilver..
        /// </summary>
        internal static string _30690 {
            get {
                return ResourceManager.GetString(":30690", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A historian once wrote of a great beast that lurked off the coast of Orr—possibly a living Champion of Zhaitan. Although she hasn&apos;t been seen for a century past, her kin still roam the dark waters..
        /// </summary>
        internal static string _30691 {
            get {
                return ResourceManager.GetString(":30691", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dare this historian say, the Moot should only be brandished by the most charismatic of warriors. When drawn, your foe may be blinded by its grandiose display of light and splendor..
        /// </summary>
        internal static string _30692 {
            get {
                return ResourceManager.GetString(":30692", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most renowned thief in Kryta had a couple of calling cards—drove the Lionguard mad. She always left two things behind: a trail of confetti and a note that read &quot;I can run faster than a centaur!&quot;.
        /// </summary>
        internal static string _30693 {
            get {
                return ResourceManager.GetString(":30693", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast in the likeness of Forge Ironstrike, this rifle was crafted as a tribute to his battle against the Flame Imperator. When Kalla fell in the Plains of Golghein, Ironstrike silenced the traitor..
        /// </summary>
        internal static string _30694 {
            get {
                return ResourceManager.GetString(":30694", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meteorlogicus was designed by a sylvari astrologer, Surya — a love letter to the sky. She once used the orrery to trace a thunderous cloud that lurked on the horizon. She knew then: a dragon had awoken..
        /// </summary>
        internal static string _30695 {
            get {
                return ResourceManager.GetString(":30695", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The Flameseeker Prophecies&quot; is an ancient tome containing near-complete proclamations of the future as foreseen by the dragon Glint. The final chapter is intentionally left unwritten....
        /// </summary>
        internal static string _30696 {
            get {
                return ResourceManager.GetString(":30696", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Although the vast, impenetrable Unending Ocean has been left unexplored for a century past, fishermen lingering just outside the expanse often catch glimpses of something magnificent..
        /// </summary>
        internal static string _30697 {
            get {
                return ResourceManager.GetString(":30697", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casters and archivists alike worship the iridescent glow that the Bifrost emits. Although the source of its magic is unknown, its luminous aura may hint of realms bygone—tucked away in the Mists..
        /// </summary>
        internal static string _30698 {
            get {
                return ResourceManager.GetString(":30698", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interwoven with an impression of a dragon whose name Tyria has yet to learn, Bolt is imbued with the strength of a storm–swelling inside like a thunderous inferno, eager to aid its wielder in combat..
        /// </summary>
        internal static string _30699 {
            get {
                return ResourceManager.GetString(":30699", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Cutha woke, he was greeted by sounds of panic and flame. He ran to the window just in time to witness a dragon perch on a nearby rooftop. &quot;Rodgort,&quot; they whispered. &quot;Rodgort is my name.&quot;.
        /// </summary>
        internal static string _30700 {
            get {
                return ResourceManager.GetString(":30700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;I&apos;ve studied the krait for some time, but never have I seen anything else quite like that. One of their shamans performed a ritual on one of their dead—undeniably dead—and it was living once again!&quot;.
        /// </summary>
        internal static string _30701 {
            get {
                return ResourceManager.GetString(":30701", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A norn ballad recounts a quarrel between the Great Wolf and a serpent who sought to become a Spirit of the Wild: O little snake, do you have what it takes? Howl, howl—open the gate..
        /// </summary>
        internal static string _30702 {
            get {
                return ResourceManager.GetString(":30702", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is said that when Dwayna woke each morning, she gifted her followers with the warmth of dawn. All of the creatures in Tyria stirred from their slumber to witness the glorious sunrise..
        /// </summary>
        internal static string _30703 {
            get {
                return ResourceManager.GetString(":30703", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While the other gods slept, Grenth took up his throne—beckoning his companions to dance and howl beneath the stars. It was said that his powers were most potent when the moon was highest in the sky..
        /// </summary>
        internal static string _30704 {
            get {
                return ResourceManager.GetString(":30704", resourceCulture);
            }
        }
    }
}
