//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegendaryArmory.Strings {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UI {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("LegendaryArmory.Strings.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AccountBindOnUse {
            get {
                return ResourceManager.GetString("AccountBindOnUse", resourceCulture);
            }
        }
        
        internal static string AccountBound {
            get {
                return ResourceManager.GetString("AccountBound", resourceCulture);
            }
        }
        
        internal static string allTypes {
            get {
                return ResourceManager.GetString("allTypes", resourceCulture);
            }
        }
        
        internal static string allWeights {
            get {
                return ResourceManager.GetString("allWeights", resourceCulture);
            }
        }
        
        internal static string ArmoryHint {
            get {
                return ResourceManager.GetString("ArmoryHint", resourceCulture);
            }
        }
        
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        internal static string Boots {
            get {
                return ResourceManager.GetString("Boots", resourceCulture);
            }
        }
        
        internal static string Coat {
            get {
                return ResourceManager.GetString("Coat", resourceCulture);
            }
        }
        
        internal static string generation {
            get {
                return ResourceManager.GetString("generation", resourceCulture);
            }
        }
        
        internal static string Gloves {
            get {
                return ResourceManager.GetString("Gloves", resourceCulture);
            }
        }
        
        internal static string Heavy {
            get {
                return ResourceManager.GetString("Heavy", resourceCulture);
            }
        }
        
        internal static string Helm {
            get {
                return ResourceManager.GetString("Helm", resourceCulture);
            }
        }
        
        internal static string Leggings {
            get {
                return ResourceManager.GetString("Leggings", resourceCulture);
            }
        }
        
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        internal static string Mainhand {
            get {
                return ResourceManager.GetString("Mainhand", resourceCulture);
            }
        }
        
        internal static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        internal static string Offhand {
            get {
                return ResourceManager.GetString("Offhand", resourceCulture);
            }
        }
        
        internal static string Shoulders {
            get {
                return ResourceManager.GetString("Shoulders", resourceCulture);
            }
        }
        
        internal static string Trinket {
            get {
                return ResourceManager.GetString("Trinket", resourceCulture);
            }
        }
        
        internal static string TwoHand {
            get {
                return ResourceManager.GetString("TwoHand", resourceCulture);
            }
        }
        
        internal static string UpgradeComponent {
            get {
                return ResourceManager.GetString("UpgradeComponent", resourceCulture);
            }
        }
        
        internal static string HelmAquatic {
            get {
                return ResourceManager.GetString("HelmAquatic", resourceCulture);
            }
        }
    }
}
